# Generated by Django 3.2.8 on 2021-10-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Address',
        ),
    ]
