# Generated by Django 3.2.8 on 2021-11-03 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_remove_employees_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
