# Generated by Django 3.2.8 on 2021-11-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('DOJ', models.DateField()),
                ('Place', models.CharField(max_length=100)),
                ('Username', models.CharField(default=None, max_length=50)),
                ('Password', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
