# Generated by Django 3.2.8 on 2021-11-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0005_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='up_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Filename', models.CharField(max_length=100)),
            ],
        ),
    ]
